# Generated by Django 3.1.5 on 2021-06-29 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_name', models.CharField(blank=True, max_length=200, null=True)),
                ('token_symbol', models.CharField(blank=True, max_length=200, null=True)),
                ('token_description', models.TextField(blank=True, max_length=2000, null=True)),
                ('presale', models.CharField(blank=True, default='No', max_length=50, null=True)),
                ('token_logo_link', models.CharField(blank=True, max_length=2000, null=True)),
                ('launch_date', models.DateField(blank=True, null=True)),
                ('is_coin_launched', models.CharField(blank=True, default='Yes', max_length=50, null=True)),
                ('smart_chain_address', models.TextField(blank=True, max_length=1000, null=True)),
                ('ethereum_address', models.TextField(blank=True, max_length=1000, null=True)),
                ('other_links', models.TextField(blank=True, max_length=2000, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('telegram', models.CharField(blank=True, max_length=1000, null=True)),
                ('twitter', models.CharField(blank=True, max_length=1000, null=True)),
                ('reddit', models.CharField(blank=True, max_length=1000, null=True)),
                ('coin_status', models.CharField(blank=True, default='Listed', max_length=100, null=True)),
                ('is_promoted_coin', models.CharField(blank=True, default='No', max_length=10, null=True)),
                ('added_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='userCoin')),
            ],
            options={
                'db_table': 'coins_model',
            },
        ),
        migrations.CreateModel(
            name='NewsLetterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_email_data', encrypted_fields.fields.EncryptedCharField(max_length=200)),
                ('email', encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='_email_data', hash_key='d2465e886a5f91ca6930c77881e0378dc81b5216b7a9758c12c760f4d53a3a3c', max_length=66, null=True)),
                ('subscribed_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'newsletter_model',
            },
        ),
        migrations.CreateModel(
            name='VotesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, default=0, null=True)),
                ('user_ip', models.CharField(blank=True, max_length=200, null=True)),
                ('vote_status', models.CharField(blank=True, default='Approved', max_length=100, null=True)),
                ('vote_added_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('Coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsection.coinsmodel', verbose_name='coin_vote')),
            ],
            options={
                'db_table': 'coin_votes_model',
            },
        ),
        migrations.CreateModel(
            name='ImpressionsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impression_text', models.TextField(blank=True, max_length=2000, null=True)),
                ('impression_added_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('Coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsection.coinsmodel', verbose_name='coin_impression')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='userImpression')),
            ],
            options={
                'db_table': 'impressions_model',
            },
        ),
    ]
