# Generated by Django 3.1.5 on 2021-07-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinsmodel',
            name='coin_slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='coinsmodel',
            name='launch_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
