# Generated by Django 3.1.5 on 2021-07-04 10:50

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('usersection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='_fullname_data',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=255, null=True, verbose_name='fullname'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='_username_data',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=100, null=True, verbose_name='username'),
        ),
    ]
